import { CookingItem } from "./types";

// 실제 API 대신 내부 데이터로 구성한 "요리" 옵션 풀.
// 한 번 장을 보면 여러 끼니를 해결할 수 있다는 점을 반영한다.
export const COOKING_POOL: CookingItem[] = [
  {
    id: "cook_curry",
    type: "cooking",
    menuName: "카레",
    totalCost: 12000,
    meals: 4,
    pricePerMeal: 3000,
    category: "한식",
    tags: ["간단", "든든함", "반복가능"],
    repeatable: 4,
  },
  {
    id: "cook_kimchi_fried_rice",
    type: "cooking",
    menuName: "김치볶음밥",
    totalCost: 8000,
    meals: 3,
    pricePerMeal: 2667,
    category: "한식",
    tags: ["간단", "매운맛", "반복가능"],
    repeatable: 3,
  },
  {
    id: "cook_doenjang_jjigae",
    type: "cooking",
    menuName: "된장찌개",
    totalCost: 10000,
    meals: 3,
    pricePerMeal: 3333,
    category: "한식",
    tags: ["든든함", "집밥"],
    repeatable: 3,
  },
  {
    id: "cook_egg_fried_rice",
    type: "cooking",
    menuName: "계란볶음밥",
    totalCost: 6000,
    meals: 3,
    pricePerMeal: 2000,
    category: "한식",
    tags: ["간단", "가벼움", "반복가능"],
    repeatable: 3,
  },
  {
    id: "cook_pasta",
    type: "cooking",
    menuName: "토마토 파스타",
    totalCost: 11000,
    meals: 3,
    pricePerMeal: 3667,
    category: "양식",
    tags: ["면", "든든함"],
    repeatable: 2,
  },
  {
    id: "cook_ramen_plus",
    type: "cooking",
    menuName: "라면+계란+파",
    totalCost: 5000,
    meals: 2,
    pricePerMeal: 2500,
    category: "분식",
    tags: ["면", "간단", "반복가능"],
    repeatable: 4,
  },
  {
    id: "cook_bulgogi",
    type: "cooking",
    menuName: "간장불고기덮밥",
    totalCost: 15000,
    meals: 4,
    pricePerMeal: 3750,
    category: "한식",
    tags: ["고기", "든든함"],
    repeatable: 2,
  },
  {
    id: "cook_kongnamul_gukbap",
    type: "cooking",
    menuName: "콩나물국밥",
    totalCost: 9000,
    meals: 3,
    pricePerMeal: 3000,
    category: "한식",
    tags: ["든든함", "해장"],
    repeatable: 3,
  },
];
