import { CookingItem } from "./types";

// 실제 API 대신 내부 데이터로 구성한 "요리" 옵션 풀.
// 가격은 "자취방에 기본 양념/식용유/쌀은 어느 정도 있다"는 전제 하에, 이번에 추가로 장보는 비용 기준이다.
// (UI에는 "장보기 예상" 문구로 표시됨)
// 한 번 장을 보면 여러 끼니를 해결할 수 있다는 점을 반영한다.
export const COOKING_POOL: CookingItem[] = [
  {
    id: "cook_curry",
    type: "cooking",
    menuName: "카레",
    totalCost: 13000,
    meals: 4,
    pricePerMeal: 3250,
    category: "한식",
    tags: ["간단", "든든함", "반복가능"],
    repeatable: 4,
  },
  {
    id: "cook_kimchi_fried_rice",
    type: "cooking",
    menuName: "김치볶음밥",
    totalCost: 7000,
    meals: 3,
    pricePerMeal: 2333,
    category: "한식",
    tags: ["간단", "매운맛", "밥"],
    repeatable: 3,
  },
  {
    id: "cook_egg_fried_rice",
    type: "cooking",
    menuName: "계란볶음밥",
    totalCost: 6500,
    meals: 3,
    pricePerMeal: 2167,
    category: "한식",
    tags: ["간단", "가벼움", "절약"],
    repeatable: 3,
  },
  {
    id: "cook_tuna_mayo_rice",
    type: "cooking",
    menuName: "참치마요덮밥",
    totalCost: 8500,
    meals: 3,
    pricePerMeal: 2833,
    category: "한식",
    tags: ["밥", "참치", "간단"],
    repeatable: 2,
  },
  {
    id: "cook_doenjang_jjigae",
    type: "cooking",
    menuName: "된장찌개",
    totalCost: 10500,
    meals: 3,
    pricePerMeal: 3500,
    category: "한식",
    tags: ["국물", "집밥", "든든함"],
    repeatable: 3,
  },
  {
    id: "cook_kimchi_jjigae",
    type: "cooking",
    menuName: "김치찌개",
    totalCost: 12000,
    meals: 3,
    pricePerMeal: 4000,
    category: "한식",
    tags: ["국물", "매운맛", "든든함"],
    repeatable: 3,
  },
  {
    id: "cook_kongnamul_gukbap",
    type: "cooking",
    menuName: "콩나물국밥",
    totalCost: 8500,
    meals: 3,
    pricePerMeal: 2833,
    category: "한식",
    tags: ["국물", "해장", "절약"],
    repeatable: 3,
  },
  {
    id: "cook_bulgogi",
    type: "cooking",
    menuName: "간장불고기덮밥",
    totalCost: 16000,
    meals: 4,
    pricePerMeal: 4000,
    category: "한식",
    tags: ["고기", "든든함", "밥"],
    repeatable: 2,
  },
  {
    id: "cook_pasta",
    type: "cooking",
    menuName: "토마토 파스타",
    totalCost: 11500,
    meals: 3,
    pricePerMeal: 3833,
    category: "양식",
    tags: ["면", "양식", "든든함"],
    repeatable: 2,
  },
  {
    id: "cook_ramen_plus",
    type: "cooking",
    menuName: "라면+계란+파",
    totalCost: 5500,
    meals: 2,
    pricePerMeal: 2750,
    category: "분식",
    tags: ["면", "간단", "초절약"],
    repeatable: 2,
  },
];
