import { KakaoPlace } from "./types";

// Kakao API 키가 없거나 호출이 실패했을 때 화면이 깨지지 않도록 제공하는
// 안암역 근처 최소 fallback 데이터. 실제 상호명을 참고해 구성했다.
export const FALLBACK_CENTER = { x: 127.0287, y: 37.5862 }; // 안암역 대략 좌표

export const FALLBACK_RESTAURANTS: KakaoPlace[] = [
  {
    id: "fallback_1",
    place_name: "고른햇살",
    category_name: "음식점 > 한식 > 백반,가정식",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 고려대로",
    x: "127.0299",
    y: "37.5864",
    distance: "420",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_2",
    place_name: "안암김밥천국",
    category_name: "음식점 > 분식 > 김밥",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 안암로",
    x: "127.0292",
    y: "37.5858",
    distance: "260",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_3",
    place_name: "고대돈까스",
    category_name: "음식점 > 일식 > 돈까스,우동",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 고려대로",
    x: "127.0301",
    y: "37.5871",
    distance: "610",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_4",
    place_name: "안암마라탕",
    category_name: "음식점 > 중식 > 마라탕",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 안암로",
    x: "127.0295",
    y: "37.5855",
    distance: "340",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_5",
    place_name: "참이맛있는집",
    category_name: "음식점 > 한식 > 찌개,전골",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 고려대로",
    x: "127.0305",
    y: "37.5849",
    distance: "780",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_6",
    place_name: "안암국수",
    category_name: "음식점 > 한식 > 국수",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 안암로",
    x: "127.0288",
    y: "37.5849",
    distance: "310",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_7",
    place_name: "교촌치킨 안암점",
    category_name: "음식점 > 치킨 > 프라이드",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 안암로",
    x: "127.0311",
    y: "37.5865",
    distance: "690",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_8",
    place_name: "안암파스타",
    category_name: "음식점 > 양식 > 파스타",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 고려대로",
    x: "127.0315",
    y: "37.5842",
    distance: "980",
    place_url: "https://map.kakao.com",
  },
];

export const FALLBACK_CONVENIENCE: KakaoPlace[] = [
  {
    id: "fallback_cs_1",
    place_name: "CU 안암역점",
    category_name: "가정,생활 > 편의점 > CU",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 안암로",
    x: "127.0290",
    y: "37.5860",
    distance: "180",
    place_url: "https://map.kakao.com",
  },
  {
    id: "fallback_cs_2",
    place_name: "GS25 고려대점",
    category_name: "가정,생활 > 편의점 > GS25",
    address_name: "서울 성북구 안암동5가",
    road_address_name: "서울 성북구 고려대로",
    x: "127.0303",
    y: "37.5873",
    distance: "530",
    place_url: "https://map.kakao.com",
  },
];
